# Generated by Django 3.2 on 2021-04-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='category',
            field=models.CharField(default='category text here', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='extra_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='main_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='size_mm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
