# Generated by Django 3.2 on 2021-04-19 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame_manager', '0004_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
