# Generated by Django 3.2 on 2021-09-06 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frame_manager', '0005_buyer_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='buyer',
            name='tx_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyer',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
